### ISSUE TITLE
How do you check if two rectangles overlap with each other?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#74]
How do you check if two rectangles overlap with each other?

**Comment by Shubhcs01** [comment]
I would like to work on this issue.

**Comment by mohitmishra786** [comment]
@Shubhcs01 sure

**Comment by Shubhcs01** [comment]
@mohitmishra786 this repo is excluded from hacktoberfest 2022.

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Comment by Shubhcs01** [comment]
> This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.
> 
> Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.
> 
> Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

Yeah! Thanks for informing😊. This is my first time that's why I didn't knew about these spammy repos.
